# General properties - Helidon and OpenLiberty
readFromFile=true

# ---- Helidon specific: Microprofile server properties -----
server.port=8080
server.host=0.0.0.0

# Change the following to true to enable the optional MicroProfile Metrics REST.request metrics
metrics.rest-request.enabled=false

# Vertex AI Configuration
ai.location=eu
ai.model=gemini-3.8-flash
# REST Client URLs
vertex-ai-api/mp-rest/url=https://aiplatform.eu.rep.googleapis.com
model-armor-api/mp-rest/url=https://networksecurity.googleapis.com
