# *** File required by Quarkus to add resource files that are outside META-INF/resources ***


# Quarkus Config
readFromFile=true
quarkus.native.additional-build-args=-H:ResourceConfigurationFiles=resources-config.json
vertex-ai-api/mp-rest/url=https://${ai.location}-aiplatform.googleapis.com
model-armor-api/mp-rest/url=https://networksecurity.googleapis.com

# Vertex AI Configuration
ai.location=europe-west1
ai.model=gemini-3.8-flash
